function  [hPlotAxes,hOpenMenuitem,hNewMenuitem,hCloseMenuitem] = TecPIV_DesignMainFigure(hMainFigure,myhandles)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

% Create the axes
hPlotAxes = axes(...    
    'Parent', hMainFigure, ...
    'Units', 'normalized', ...
    'HandleVisibility','callback', ...
    'Position',[0.048 0.115 0.940 0.86]);

% create the menus
% Project menu
hProjectMenu = uimenu(...       
    'Parent',hMainFigure,...
    'HandleVisibility','callback', ...
    'Label','Project');

% Open Project menu item
hOpenMenuitem = uimenu(...       
    'Parent',hProjectMenu,...
    'Label','Open',...
    'HandleVisibility','callback', ...
    'Callback', @hOpenMenuitemCallback);
% New Project menu item
hNewMenuitem = uimenu(...       
    'Parent',hProjectMenu,...
    'Label','New',...
    'HandleVisibility','callback', ...
    'Callback', @hNewMenuitemCallback);

% Save & Close Project menu item
hCloseMenuitem = uimenu(...       
    'Parent',hProjectMenu,...
    'Label','Save & Close',...
    'Separator','on',...
    'HandleVisibility','callback', ...
    'Callback', @hCloseMenuitemCallback);

end

